defaults:
  - text2semantic_pretrain_small
  - _self_

project: text2semantic_pretrain_large_dual_ar

# Model Configuration
model:
  model:
    config:
      n_layer: 36
      n_head: 20
      dim: 1280
