version: '3.8'

services:
  fish-speech:
    build: .
    volumes:
      - ./data:/exp/data
      - ./raw_data:/exp/raw_data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null

